services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "5890:8000"
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG:-False}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DB_DEFAULT_NAME: ${DB_DEFAULT_NAME}
      DB_DEFAULT_USER: ${DB_DEFAULT_USER}
      DB_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
      DB_DEFAULT_HOST: ${DB_DEFAULT_HOST}
      DB_DEFAULT_PORT: ${DB_DEFAULT_PORT:-5432}
      DB_IMEDX_NAME: ${DB_IMEDX_NAME}
      DB_IMEDX_USER: ${DB_IMEDX_USER}
      DB_IMEDX_PASSWORD: ${DB_IMEDX_PASSWORD}
      DB_IMEDX_HOST: ${DB_IMEDX_HOST}
      DB_IMEDX_PORT: ${DB_IMEDX_PORT:-5432}
