# Generated by Django 5.1.4 on 2026-09-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_vet_manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='ตำแหน่ง')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินเดือน')),
                ('monthly_data', models.JSONField(default=dict, verbose_name='ข้อมูลรายเดือน (Jan-Dec)')),
                ('base_branch_id', models.IntegerField(blank=True, null=True, verbose_name='รหัสสาขาหลัก')),
                ('base_sub_branch_id', models.IntegerField(blank=True, null=True, verbose_name='รหัสสาขาย่อย')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
            ],
            options={
                'verbose_name': 'VET Manpower Budget',
                'verbose_name_plural': 'VET Manpower Budgets',
                'db_table': 'ebudget_vet_manpower',
            },
        ),
    ]
