# Generated by Django 5.1.4 on 2026-09-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='document_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร'),
        ),
        migrations.AlterField(
            model_name='ebudget_vet_manpower',
            name='base_branch_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก'),
        ),
        migrations.AlterField(
            model_name='ebudget_vet_manpower',
            name='base_sub_branch_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาย่อย'),
        ),
    ]
