# Generated by Django 5.1.4 on 2026-09-05 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_ebudget_vet_manpower_document_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebudget_vet_manpower',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='ebudget_vet_manpower',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
