# Generated by Django 5.1.4 on 2026-09-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_alter_ebudget_vet_manpower_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_non_vet_manpower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=255, verbose_name='ตำแหน่ง')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินเดือน')),
                ('position_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าวัดระดับ/ตำแหน่ง')),
                ('monthly_data', models.JSONField(default=dict, verbose_name='ข้อมูลรายเดือน (Jan-Dec)')),
                ('base_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก')),
                ('base_sub_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาย่อย')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
            ],
            options={
                'verbose_name': 'NON VET Manpower Budget',
                'verbose_name_plural': 'NON VET Manpower Budgets',
                'db_table': 'ebudget_non_vet_manpower',
            },
        ),
    ]
