# Generated by Django 5.1.4 on 2026-09-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0004_ebudget_non_vet_manpower'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_position_adjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_position_name', models.CharField(max_length=255, verbose_name='ตำแหน่งเดิม')),
                ('new_position_name', models.CharField(max_length=255, verbose_name='ตำแหน่งใหม่')),
                ('old_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินเดือนเดิม')),
                ('old_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าวัดระดับ/ตำแหน่งเดิม')),
                ('new_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินเดือนใหม่')),
                ('new_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าวัดระดับ/ตำแหน่งใหม่')),
                ('monthly_data', models.JSONField(default=dict, verbose_name='ข้อมูลจำนวนคนรายเดือน (Jan-Dec)')),
                ('base_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร')),
                ('create_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', models.DateTimeField(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
            ],
            options={
                'verbose_name': 'Position Adjustment',
                'verbose_name_plural': 'Position Adjustments',
                'db_table': 'ebudget_position_adjustment',
            },
        ),
    ]
