# Generated by Django 5.1.4 on 2026-09-06 18:04

import budget_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0005_ebudget_position_adjustment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebudget_non_vet_manpower',
            name='create_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='ebudget_non_vet_manpower',
            name='modify_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='ebudget_position_adjustment',
            name='create_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='ebudget_position_adjustment',
            name='modify_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='ebudget_vet_manpower',
            name='create_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='ebudget_vet_manpower',
            name='modify_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
