# Generated by Django 5.1.4 on 2026-09-07 00:10

import budget_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0007_ebudget_medical_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_computer_equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='เครื่องมือ')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาซื้อ')),
                ('monthly_data', models.JSONField(default=dict, verbose_name='ข้อมูลรายเดือน (Jan-Dec)')),
                ('base_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร')),
                ('create_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
            ],
            options={
                'verbose_name': 'Computer Equipment Budget',
                'verbose_name_plural': 'Computer Equipment Budgets',
                'db_table': 'ebudget_computer_equipment',
            },
        ),
    ]
