# Generated by Django 5.1.4 on 2026-09-07 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0008_ebudget_computer_equipment'),
        ('master_data', '0002_ebudget_budget_item_master_total_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='general_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_general_ledger_master', verbose_name='อ้างอิง General Ledger'),
        ),
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='item_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_budget_item_master', verbose_name='อ้างอิง Item Master'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='general_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_general_ledger_master', verbose_name='อ้างอิง General Ledger'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='item_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_budget_item_master', verbose_name='อ้างอิง Item Master'),
        ),
        migrations.AddField(
            model_name='ebudget_non_vet_manpower',
            name='general_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_general_ledger_master', verbose_name='อ้างอิง General Ledger'),
        ),
        migrations.AddField(
            model_name='ebudget_non_vet_manpower',
            name='item_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_budget_item_master', verbose_name='อ้างอิง Item Master'),
        ),
        migrations.AddField(
            model_name='ebudget_position_adjustment',
            name='general_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_general_ledger_master', verbose_name='อ้างอิง General Ledger'),
        ),
        migrations.AddField(
            model_name='ebudget_position_adjustment',
            name='item_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_budget_item_master', verbose_name='อ้างอิง Item Master'),
        ),
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='general_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_general_ledger_master', verbose_name='อ้างอิง General Ledger'),
        ),
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='item_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_budget_item_master', verbose_name='อ้างอิง Item Master'),
        ),
    ]
