# Generated by Django 5.1.4 on 2026-09-07 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0009_ebudget_computer_equipment_general_ledger_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMonthlyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='เดือน (1-12)')),
                ('headcount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='จำนวน (คน/ชิ้น)')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='งบประมาณ (Cost)')),
                ('comp_equip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_computer_equipment')),
                ('med_equip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_medical_equipment')),
                ('non_vet_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_non_vet_manpower')),
                ('position_adj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_position_adjustment')),
                ('vet_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_vet_manpower')),
            ],
            options={
                'verbose_name': 'Budget Monthly Detail',
                'verbose_name_plural': 'Budget Monthly Details',
                'db_table': 'ebudget_monthly_detail',
            },
        ),
    ]
