# Generated by Django 6.1.1 on 2026-09-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0010_budgetmonthlydetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebudget_computer_equipment',
            name='monthly_data',
        ),
        migrations.RemoveField(
            model_name='ebudget_medical_equipment',
            name='monthly_data',
        ),
        migrations.RemoveField(
            model_name='ebudget_non_vet_manpower',
            name='monthly_data',
        ),
        migrations.RemoveField(
            model_name='ebudget_position_adjustment',
            name='monthly_data',
        ),
        migrations.RemoveField(
            model_name='ebudget_vet_manpower',
            name='monthly_data',
        ),
    ]
