# Generated by Django 6.1.1 on 2026-09-07 18:36

import budget_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0011_remove_ebudget_computer_equipment_monthly_data_and_more'),
        ('master_data', '0002_ebudget_budget_item_master_total_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='เครื่องมือ')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาซื้อ')),
                ('base_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร')),
                ('create_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
                ('general_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_general_ledger_master', verbose_name='อ้างอิง General Ledger')),
                ('item_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_budget_item_master', verbose_name='อ้างอิง Item Master')),
            ],
            options={
                'verbose_name': 'Furniture Budget',
                'verbose_name_plural': 'Furniture Budgets',
                'db_table': 'ebudget_furniture',
            },
        ),
        migrations.AddField(
            model_name='budgetmonthlydetail',
            name='furniture_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_furniture'),
        ),
    ]
