# Generated by Django 6.1.1 on 2026-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0013_ebudget_tools_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='ebudget_furniture',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='ebudget_non_vet_manpower',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='ebudget_position_adjustment',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='ebudget_tools_equipment',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='cost_center_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center'),
        ),
    ]
