# Generated by Django 6.1.1 on 2026-09-09 21:35

import budget_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0015_general_ledger_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_gl_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_ledger_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัส General Ledger')),
                ('base_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก')),
                ('cost_center_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร')),
                ('create_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
            ],
            options={
                'verbose_name': 'GL Monthly Entry',
                'verbose_name_plural': 'GL Monthly Entries',
                'db_table': 'ebudget_gl_entry',
            },
        ),
        migrations.CreateModel(
            name='ebudget_gl_entry_monthly_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='เดือน (1-12)')),
                ('detail_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='งบประมาณที่ใช้ (เดือนนี้)')),
                ('cumulative_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ลงระหว่างเดือน (สะสม)')),
                ('gl_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_gl_entry')),
            ],
            options={
                'verbose_name': 'GL Entry Monthly Detail',
                'verbose_name_plural': 'GL Entry Monthly Details',
                'db_table': 'ebudget_gl_entry_monthly_detail',
            },
        ),
    ]
