# Generated by Django 6.1.1 on 2026-09-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0016_ebudget_gl_entry_ebudget_gl_entry_monthly_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='useful_life_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='อายุการใช้งาน (%)'),
        ),
    ]
