# Generated by Django 6.1.1 on 2026-09-11 12:54

import budget_app.models
from django.db import migrations, models


PARENT_MODEL_NAMES = [
    'ebudget_vet_manpower', 'ebudget_non_vet_manpower', 'ebudget_position_adjustment',
    'ebudget_medical_equipment', 'ebudget_computer_equipment', 'ebudget_furniture',
    'ebudget_tools_equipment', 'ebudget_gl_entry',
]


def backfill_budget_year_from_create_date(apps, schema_editor):
    """Existing rows have no budget_year yet — infer a reasonable value from
    the year they were actually entered (create_date), since that's the only
    signal available for data saved before this feature existed."""
    for model_name in PARENT_MODEL_NAMES:
        model = apps.get_model('budget_app', model_name)
        for row in model.objects.filter(budget_year__isnull=True).exclude(create_date__isnull=True):
            row.budget_year = row.create_date.year
            row.save(update_fields=['budget_year'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0017_ebudget_gl_entry_useful_life_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_frozen', models.BooleanField(default=False)),
                ('frozen_message', models.CharField(blank=True, default='ระบบอยู่ระหว่างปิดงบประมาณชั่วคราว ไม่สามารถเพิ่มหรือแก้ไขข้อมูลได้ในขณะนี้ หากมีข้อสงสัยกรุณาติดต่อฝ่ายบัญชี', max_length=500)),
                ('active_budget_year', models.PositiveIntegerField(default=2026)),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True)),
                ('modify_date', budget_app.models.Timestamp0Field(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'ebudget_system_settings',
            },
        ),
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='ebudget_furniture',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='ebudget_non_vet_manpower',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='ebudget_position_adjustment',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='ebudget_tools_equipment',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='budget_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ'),
        ),
        migrations.RunPython(backfill_budget_year_from_create_date, migrations.RunPython.noop),
    ]
