# Generated by Django 6.1.1 on 2026-09-11 13:44, hand-edited.
#
# Postgres can't auto-cast boolean -> smallint (no implicit cast path), so a
# plain AlterField here would fail at migrate time. Goes through an
# AddField -> RunPython backfill -> RemoveField -> RenameField sequence
# instead, same data-preserving pattern used in 0015_general_ledger_code.

from django.db import migrations, models


def backfill_is_frozen_int(apps, schema_editor):
    SystemSettings = apps.get_model('budget_app', 'SystemSettings')
    for row in SystemSettings.objects.all():
        row.is_frozen_int = 1 if row.is_frozen else 0
        row.save(update_fields=['is_frozen_int'])


def backfill_is_frozen_bool(apps, schema_editor):
    SystemSettings = apps.get_model('budget_app', 'SystemSettings')
    for row in SystemSettings.objects.all():
        row.is_frozen = bool(row.is_frozen_int)
        row.save(update_fields=['is_frozen'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0018_systemsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='is_frozen_int',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not Frozen'), (1, 'Frozen')], default=0),
        ),
        migrations.RunPython(backfill_is_frozen_int, backfill_is_frozen_bool),
        migrations.RemoveField(
            model_name='systemsettings',
            name='is_frozen',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='is_frozen_int',
            new_name='is_frozen',
        ),
    ]
