# Generated by Django 6.1.1 on 2026-09-11 14:01, hand-edited.
#
# Reordered so AddField runs before RemoveField, with a RunPython backfill
# in between: modify_eid/modify_date collapsed one event ("who last touched
# this row") into a single pair of columns, which stopped making sense once
# a row can represent two distinct events (who opened the freeze episode,
# who closed it). Splits that into frozen_eid/frozen_date and
# unfrozen_eid/unfrozen_date, inferring which one each existing row's
# modify_* values belong to from its is_frozen state at migration time.

import budget_app.models
from django.db import migrations, models


def backfill_frozen_unfrozen(apps, schema_editor):
    SystemSettings = apps.get_model('budget_app', 'SystemSettings')
    for row in SystemSettings.objects.all():
        if row.is_frozen:
            # Still open: the last touch was whoever froze it.
            row.frozen_eid = row.modify_eid
            row.frozen_date = row.modify_date
        else:
            # Already closed (or never frozen): best-effort — treat the
            # last touch as the unfreeze/no-op, since there's no earlier
            # freeze event recorded to recover.
            row.unfrozen_eid = row.modify_eid
            row.unfrozen_date = row.modify_date
        row.save(update_fields=['frozen_eid', 'frozen_date', 'unfrozen_eid', 'unfrozen_date'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0020_fix_systemsettings_id_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='frozen_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='frozen_eid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='unfrozen_date',
            field=budget_app.models.Timestamp0Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='unfrozen_eid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RunPython(backfill_frozen_unfrozen, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='systemsettings',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='modify_eid',
        ),
    ]
