# Generated by Django 6.1.1 on 2026-09-11 21:18

import budget_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0021_remove_systemsettings_modify_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_budget_plan_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_category', models.CharField(choices=[('ACTIVITY', 'กิจกรรมที่จะทำ'), ('PERSONNEL', 'ค่าจ้างบุคคลากร'), ('ASSET', 'ทรัพย์สินและ Software')], max_length=20, verbose_name='หมวด')),
                ('group_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสกลุ่ม')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อกลุ่ม')),
                ('item_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสรายการ')),
                ('general_ledger_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัส General Ledger')),
                ('activity_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='ประเภทกิจกรรม')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด')),
                ('controller', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ควบคุม')),
                ('budget_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='การเบิกงบ')),
                ('budget_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ')),
                ('base_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก')),
                ('cost_center_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร')),
                ('create_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
            ],
            options={
                'verbose_name': 'Budget Plan Item',
                'verbose_name_plural': 'Budget Plan Items',
                'db_table': 'ebudget_budget_plan_item',
            },
        ),
        migrations.CreateModel(
            name='ebudget_budget_plan_monthly_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], verbose_name='เดือน (1-12)')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='งบประมาณ')),
                ('plan_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_budget_plan_item')),
            ],
            options={
                'verbose_name': 'Budget Plan Monthly Detail',
                'verbose_name_plural': 'Budget Plan Monthly Details',
                'db_table': 'ebudget_budget_plan_monthly_detail',
            },
        ),
    ]
