# Generated by Django 6.1.1 on 2026-09-11 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0022_ebudget_budget_plan_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebudget_budget_plan_item',
            name='group_code',
        ),
        migrations.RemoveField(
            model_name='ebudget_budget_plan_item',
            name='group_name',
        ),
    ]
