# Generated by Django 6.1.1 on 2026-09-11 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0023_remove_ebudget_budget_plan_item_group_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebudget_budget_plan_item',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='ebudget_budget_plan_item',
            name='budget_type',
        ),
        migrations.RemoveField(
            model_name='ebudget_budget_plan_item',
            name='controller',
        ),
    ]
