# Generated by Django 6.1.1 on 2026-09-11 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0024_remove_ebudget_budget_plan_item_activity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebudget_budget_plan_item',
            name='budget_category',
            field=models.CharField(choices=[('EXTRA_REVENUE', 'รายได้เพิ่ม ที่ไม่ใช่จากการขายปกติ'), ('ACTIVITY', 'กิจกรรมที่จะทำ'), ('PERSONNEL', 'ค่าจ้างบุคคลากร'), ('ASSET', 'ทรัพย์สินและ Software')], max_length=20, verbose_name='หมวด'),
        ),
    ]
