# Generated by Django 6.1.1 on 2026-09-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0025_alter_ebudget_budget_plan_item_budget_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='detail_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด'),
        ),
    ]
