# Generated by Django 6.1.1 on 2026-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0026_ebudget_gl_entry_detail_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebudget_gl_entry',
            name='useful_life_percent',
        ),
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าเสื่อม'),
        ),
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='สัดส่วน'),
        ),
    ]
