# Generated by Django 6.1.1 on 2026-09-16 01:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0027_remove_ebudget_gl_entry_useful_life_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebudget_gl_entry',
            name='depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='ค่าเสื่อม (%)'),
        ),
        migrations.AlterField(
            model_name='ebudget_gl_entry',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='สัดส่วน (%)'),
        ),
    ]
