# Generated by Django 6.1.1 on 2026-09-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0028_alter_ebudget_gl_entry_depreciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_budget_plan_item',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_furniture',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_non_vet_manpower',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_position_adjustment',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_tools_equipment',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก'),
        ),
    ]
