# Generated by Django 6.1.1 on 2026-09-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0029_ebudget_budget_plan_item_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_budget_plan_item',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_budget_plan_item',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_furniture',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_furniture',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_gl_entry',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_non_vet_manpower',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_non_vet_manpower',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_position_adjustment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_position_adjustment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_tools_equipment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_tools_equipment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก'),
        ),
        migrations.AddField(
            model_name='ebudget_vet_manpower',
            name='status',
            field=models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ'),
        ),
    ]
