# Generated by Django 6.1.1 on 2026-09-23 16:56

import budget_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0030_ebudget_budget_plan_item_cancel_reason_and_more'),
        ('master_data', '0012_alter_ebudget_general_ledger_master_depreciation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='รถยนต์')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาซื้อ')),
                ('base_branch_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='รหัสสาขาหลัก')),
                ('department_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสแผนก')),
                ('cost_center_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost Center')),
                ('document_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่เอกสาร')),
                ('general_ledger_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัส General Ledger')),
                ('budget_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='ปีงบประมาณ')),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVED', 'อนุมัติแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PENDING', max_length=10, verbose_name='สถานะ')),
                ('cancel_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลการยกเลิก')),
                ('create_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่สร้าง')),
                ('create_eid', models.CharField(max_length=50, verbose_name='ผู้สร้าง (Employee ID)')),
                ('modify_date', budget_app.models.Timestamp0Field(blank=True, null=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('modify_eid', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผู้แก้ไข (Employee ID)')),
                ('item_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master_data.ebudget_budget_item_master', verbose_name='อ้างอิง Item Master')),
            ],
            options={
                'verbose_name': 'CAR Budget',
                'verbose_name_plural': 'CAR Budgets',
                'db_table': 'ebudget_car',
            },
        ),
        migrations.AddField(
            model_name='budgetmonthlydetail',
            name='car_equip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_details', to='budget_app.ebudget_car'),
        ),
    ]
