# Generated by Django 6.1.1 on 2026-09-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0031_ebudget_car_budgetmonthlydetail_car_equip'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_car',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='ebudget_computer_equipment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='ebudget_furniture',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='ebudget_medical_equipment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='ebudget_tools_equipment',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รายละเอียด'),
        ),
    ]
