# Generated by Django 5.1.4 on 2026-09-04 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_budget_category_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.CharField(max_length=50, unique=True, verbose_name='รหัส category')),
                ('category_name', models.CharField(max_length=255, verbose_name='ชื่อ category')),
            ],
        ),
        migrations.CreateModel(
            name='ebudget_general_ledger_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_code', models.CharField(max_length=50, unique=True, verbose_name='รหัส general ledger')),
                ('gl_name', models.CharField(max_length=255, verbose_name='ชื่อ general_ledger')),
            ],
        ),
        migrations.CreateModel(
            name='ebudget_budget_sub_category_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_code', models.CharField(max_length=50, unique=True, verbose_name='รหัส sub_category')),
                ('sub_category_name', models.CharField(max_length=255, verbose_name='ชื่อ sub_category')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_data.ebudget_budget_category_master', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='ebudget_budget_item_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='ชื่อตำแหน่ง/รายการ')),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินเดือน')),
                ('estimated_shift_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าเวรโดยประมาณ')),
                ('position_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าวัดระดับ/ตำแหน่ง')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาซื้อ')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.ebudget_budget_category_master', verbose_name='Category')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.ebudget_budget_sub_category_master', verbose_name='Sub Category')),
                ('general_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.ebudget_general_ledger_master', verbose_name='General Ledger')),
            ],
        ),
    ]
