# Generated by Django 5.1.4 on 2026-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_budget_item_master',
            name='total_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='รวม'),
        ),
    ]
