# Generated by Django 6.1.1 on 2026-09-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0002_ebudget_budget_item_master_total_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ebudget_cost_center_master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center_name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อ Cost Center')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='คำอธิบาย')),
            ],
        ),
    ]
