# Generated by Django 6.1.1 on 2026-09-11 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0006_seed_budget_category_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_general_ledger_master',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master_data.ebudget_budget_category_master', verbose_name='Category'),
        ),
    ]
