# Generated by Django 6.1.1 on 2026-09-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0009_rename_c03_category_to_budget_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_general_ledger_master',
            name='depreciation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าเสื่อม'),
        ),
        migrations.AddField(
            model_name='ebudget_general_ledger_master',
            name='proportion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='สัดส่วน'),
        ),
    ]
