# Generated by Django 6.1.1 on 2026-09-16 01:19

from django.db import migrations, models


def copy_gl_code_forward(apps, schema_editor):
    """Preserve the general_ledger FK data (just populated on 176 rows) as
    general_ledger_code before the FK column is dropped below."""
    ItemMaster = apps.get_model('master_data', 'ebudget_budget_item_master')
    items = list(
        ItemMaster.objects.filter(general_ledger_id__isnull=False).select_related('general_ledger')
    )
    for item in items:
        item.general_ledger_code = item.general_ledger.gl_code
    ItemMaster.objects.bulk_update(items, ['general_ledger_code'])


def copy_gl_code_backward(apps, schema_editor):
    """Reverse: resolve general_ledger_code back to the matching GL master
    row's id, so `migrate` backward restores the FK relationship."""
    ItemMaster = apps.get_model('master_data', 'ebudget_budget_item_master')
    GLMaster = apps.get_model('master_data', 'ebudget_general_ledger_master')
    gl_by_code = {gl.gl_code: gl.id for gl in GLMaster.objects.all()}
    items = list(ItemMaster.objects.exclude(general_ledger_code__isnull=True))
    for item in items:
        item.general_ledger_id = gl_by_code.get(item.general_ledger_code)
    ItemMaster.objects.bulk_update(items, ['general_ledger_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('master_data', '0010_ebudget_general_ledger_master_depreciation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebudget_budget_item_master',
            name='general_ledger_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัส General Ledger'),
        ),
        migrations.RunPython(copy_gl_code_forward, copy_gl_code_backward),
        migrations.RemoveField(
            model_name='ebudget_budget_item_master',
            name='general_ledger',
        ),
    ]
